# Generated by Django 5.0.2 on 2024-03-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=50)),
                ('Family', models.CharField(max_length=50)),
                ('Email', models.IntegerField(max_length=100)),
                ('Password', models.IntegerField(max_length=100)),
            ],
        ),
    ]
